# Generated by Django 5.2.7 on 2025-10-19 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Raça')),
                ('observacoes_manejo', models.TextField(blank=True, verbose_name='Observações de Manejo')),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racas', to='management.tipoanimal')),
            ],
            options={
                'unique_together': {('tipo_animal', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.raca')),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.tipoanimal')),
            ],
        ),
    ]
