# Generated by Django 5.2.7 on 2025-10-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_popular_tipos_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoanimal',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classe do Ícone'),
        ),
    ]
