# Generated by Django 5.2.7 on 2025-10-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_tipoanimal_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
